/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SRouteImport } from './routes/s'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccessRouteImport } from './routes/access'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as ProtocolSealRouteImport } from './routes/protocol.seal'
import { Route as ProtocolIdentityRouteImport } from './routes/protocol.identity'
import { Route as ProtocolDistributeRouteImport } from './routes/protocol.distribute'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ApiWebhooksNearpaymentsRouteImport } from './routes/api/webhooks/nearpayments'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SRoute = SRouteImport.update({
  id: '/s',
  path: '/s',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessRoute = AccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtocolSealRoute = ProtocolSealRouteImport.update({
  id: '/protocol/seal',
  path: '/protocol/seal',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtocolIdentityRoute = ProtocolIdentityRouteImport.update({
  id: '/protocol/identity',
  path: '/protocol/identity',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtocolDistributeRoute = ProtocolDistributeRouteImport.update({
  id: '/protocol/distribute',
  path: '/protocol/distribute',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksNearpaymentsRoute = ApiWebhooksNearpaymentsRouteImport.update({
  id: '/api/webhooks/nearpayments',
  path: '/api/webhooks/nearpayments',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/s': typeof SRoute
  '/security': typeof SecurityRoute
  '/terms': typeof TermsRoute
  '/vault': typeof VaultRoute
  '/verify': typeof VerifyRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/protocol/distribute': typeof ProtocolDistributeRoute
  '/protocol/identity': typeof ProtocolIdentityRoute
  '/protocol/seal': typeof ProtocolSealRoute
  '/blog/': typeof BlogIndexRoute
  '/api/webhooks/nearpayments': typeof ApiWebhooksNearpaymentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/s': typeof SRoute
  '/security': typeof SecurityRoute
  '/terms': typeof TermsRoute
  '/vault': typeof VaultRoute
  '/verify': typeof VerifyRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/protocol/distribute': typeof ProtocolDistributeRoute
  '/protocol/identity': typeof ProtocolIdentityRoute
  '/protocol/seal': typeof ProtocolSealRoute
  '/blog': typeof BlogIndexRoute
  '/api/webhooks/nearpayments': typeof ApiWebhooksNearpaymentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/s': typeof SRoute
  '/security': typeof SecurityRoute
  '/terms': typeof TermsRoute
  '/vault': typeof VaultRoute
  '/verify': typeof VerifyRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/protocol/distribute': typeof ProtocolDistributeRoute
  '/protocol/identity': typeof ProtocolIdentityRoute
  '/protocol/seal': typeof ProtocolSealRoute
  '/blog/': typeof BlogIndexRoute
  '/api/webhooks/nearpayments': typeof ApiWebhooksNearpaymentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access'
    | '/admin'
    | '/contact'
    | '/docs'
    | '/faq'
    | '/privacy'
    | '/s'
    | '/security'
    | '/terms'
    | '/vault'
    | '/verify'
    | '/blog/$slug'
    | '/protocol/distribute'
    | '/protocol/identity'
    | '/protocol/seal'
    | '/blog/'
    | '/api/webhooks/nearpayments'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access'
    | '/admin'
    | '/contact'
    | '/docs'
    | '/faq'
    | '/privacy'
    | '/s'
    | '/security'
    | '/terms'
    | '/vault'
    | '/verify'
    | '/blog/$slug'
    | '/protocol/distribute'
    | '/protocol/identity'
    | '/protocol/seal'
    | '/blog'
    | '/api/webhooks/nearpayments'
  id:
    | '__root__'
    | '/'
    | '/access'
    | '/admin'
    | '/contact'
    | '/docs'
    | '/faq'
    | '/privacy'
    | '/s'
    | '/security'
    | '/terms'
    | '/vault'
    | '/verify'
    | '/blog/$slug'
    | '/protocol/distribute'
    | '/protocol/identity'
    | '/protocol/seal'
    | '/blog/'
    | '/api/webhooks/nearpayments'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessRoute: typeof AccessRoute
  AdminRoute: typeof AdminRoute
  ContactRoute: typeof ContactRoute
  DocsRoute: typeof DocsRoute
  FaqRoute: typeof FaqRoute
  PrivacyRoute: typeof PrivacyRoute
  SRoute: typeof SRoute
  SecurityRoute: typeof SecurityRoute
  TermsRoute: typeof TermsRoute
  VaultRoute: typeof VaultRoute
  VerifyRoute: typeof VerifyRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ProtocolDistributeRoute: typeof ProtocolDistributeRoute
  ProtocolIdentityRoute: typeof ProtocolIdentityRoute
  ProtocolSealRoute: typeof ProtocolSealRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ApiWebhooksNearpaymentsRoute: typeof ApiWebhooksNearpaymentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s': {
      id: '/s'
      path: '/s'
      fullPath: '/s'
      preLoaderRoute: typeof SRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access': {
      id: '/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protocol/seal': {
      id: '/protocol/seal'
      path: '/protocol/seal'
      fullPath: '/protocol/seal'
      preLoaderRoute: typeof ProtocolSealRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protocol/identity': {
      id: '/protocol/identity'
      path: '/protocol/identity'
      fullPath: '/protocol/identity'
      preLoaderRoute: typeof ProtocolIdentityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protocol/distribute': {
      id: '/protocol/distribute'
      path: '/protocol/distribute'
      fullPath: '/protocol/distribute'
      preLoaderRoute: typeof ProtocolDistributeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/nearpayments': {
      id: '/api/webhooks/nearpayments'
      path: '/api/webhooks/nearpayments'
      fullPath: '/api/webhooks/nearpayments'
      preLoaderRoute: typeof ApiWebhooksNearpaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessRoute: AccessRoute,
  AdminRoute: AdminRoute,
  ContactRoute: ContactRoute,
  DocsRoute: DocsRoute,
  FaqRoute: FaqRoute,
  PrivacyRoute: PrivacyRoute,
  SRoute: SRoute,
  SecurityRoute: SecurityRoute,
  TermsRoute: TermsRoute,
  VaultRoute: VaultRoute,
  VerifyRoute: VerifyRoute,
  BlogSlugRoute: BlogSlugRoute,
  ProtocolDistributeRoute: ProtocolDistributeRoute,
  ProtocolIdentityRoute: ProtocolIdentityRoute,
  ProtocolSealRoute: ProtocolSealRoute,
  BlogIndexRoute: BlogIndexRoute,
  ApiWebhooksNearpaymentsRoute: ApiWebhooksNearpaymentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
